### ISSUE TITLE
Missing fontanero copyright

### ISSUE THREAD

**Issue by whoozle** [GSGroup/stingray-js-apps#1]
Can't see how this code ended up with GS copyright. Original game was developed for 10k Apart back in the August 2010 a few years before I joined GS. 

It would be really nice to see a link to the original game in your license plate

https://github.com/whoozle/fontanero

**Comment by ivzave** [comment]
Hi Vladimir!

Sure I will add link to original game.

Is Vladimir Menshakov <vladimir.menshakov@gmail.com> and Vladimir Zhuravlev <private.face@gmail.com> ok for copyright?

Do I need to also fix license to LGPLv3?

**Comment by whoozle** [comment]
@ivzave you can just add link to the my github repo I suppose. 
Yes, please, license requires you to keep the license even if you distribute derived work. 

Thanks

**Comment by ivzave** [comment]
I've replaced license and added link to origin game repo, now it should be ok.
